{
	"version": 1600436155,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/fundo-sheet0.png",
		"images/bandeira-sheet0.png",
		"images/bandeiraing-sheet0.png",
		"images/dsp32semfundo-sheet0.png",
		"images/tela_fade-sheet0.png",
		"images/soundoff-sheet0.png",
		"images/soundoff-sheet1.png",
		"images/bandeira_apenas-sheet0.png",
		"images/botao_ing-sheet0.png",
		"images/botao_esp2-sheet0.png",
		"images/botao_port-sheet0.png",
		"images/placa-sheet0.png",
		"images/placa-sheet1.png",
		"images/botao_correto-sheet0.png",
		"images/botao_incorreto-sheet0.png",
		"images/fundoquiz-sheet0.png",
		"images/botao_instrucao-sheet0.png",
		"images/fundo_instrucoes-sheet0.png",
		"media/menu click 2.ogg",
		"media/ok - 4.ogg",
		"media/quiz_axtoncrolley__nodens-field-song.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}